config/routes.rb
Bloodbank::Application.routes.draw do
  resources :donors, :except => [:edit, :delete]

   root :to => 'donors#index'

end

app/models/blood_group.rb
class BloodGroup < ActiveRecord::Base
  attr_accessible :bloodgroup
  has_many :donors
end

app/models/donor.rb
class Donor < ActiveRecord::Base
  attr_accessible :blood_group_id, :contact, :email, :name, :district
  validates_presence_of :contact
  validates_presence_of :blood_group_id
  validates_presence_of :email
  validates_presence_of :name
  validates_presence_of :district
  validates_uniqueness_of :email

  belongs_to :blood_group
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/donors_controller.rb
class DonorsController < ApplicationController
  # GET /donors
  # GET /donors.json
  def index
    @donors = Donor.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @donors }
    end
  end

  # GET /donors/1
  # GET /donors/1.json
  def show
    @donor = Donor.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @donor }
    end
  end

  # GET /donors/new
  # GET /donors/new.json
  def new
    @donor = Donor.new
	@groups = BloodGroup.all
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @donor }
    end
  end

  # GET /donors/1/edit
  def edit
    @donor = Donor.find(params[:id])
	@groups = BloodGroup.all
  end

  # POST /donors
  # POST /donors.json
  def create
    @donor = Donor.new(params[:donor])
	@groups = BloodGroup.all
    respond_to do |format|
      if @donor.save
        format.html { redirect_to @donor, notice: 'Donor was successfully created.' }
        format.json { render json: @donor, status: :created, location: @donor }
      else
        format.html { render action: "new" }
        format.json { render json: @donor.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /donors/1
  # PUT /donors/1.json
  def update
    @donor = Donor.find(params[:id])

    respond_to do |format|
      if @donor.update_attributes(params[:donor])
        format.html { redirect_to @donor, notice: 'Donor was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @donor.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /donors/1
  # DELETE /donors/1.json
  def destroy
    @donor = Donor.find(params[:id])
    @donor.destroy

    respond_to do |format|
      format.html { redirect_to donors_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/donors_helper.rb
module DonorsHelper
end

app/views/donors/_form.html.erb
<%= form_for(@donor) do |f| %>
  <% if @donor.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@donor.errors.count, "error") %> prohibited this donor from being saved:</h2>

      <ul>
      <% @donor.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :contact %><br />
    <%= f.text_field :contact %>
  </div>
  <div class="field">
    <%= f.label :blood_group_id %><br />
    <%= f.collection_select(:blood_group_id, @groups, :id, :bloodgroup) %>
  </div>
  
  <div class="field">
    <%= f.label :district %><br />
    <%= f.select(:district, options_for_select([['Kasargod', 'Kasrargod'],['Kannur', 'Kannur'], ['Kozhikkode', 'Kozhikkode'],
												['Waynad', 'Waynad'],['Malappuram', 'Malappuram'],['Palakkad', 'Palakkad'],
												['Thrissur', 'Thrissur'],['Idukki', 'Idukki'],['Kottayam', 'Kottayam'],
												['Ernakulam', 'Ernakulam'],['Alappuzha', 'Alappuzha'],['Pathanamthitta', 'Pathanamthitta'],
												['Kollam', 'Kollam'],['Thiruvanathapuram', 'Thiruvanathapuram']])) %>	
  </div>	
  
  <div class="field">
    <%= f.label :email %><br />
    <%= f.email_field :email %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/donors/edit.html.erb
<h1>Editing donor</h1>

<%= render 'form' %>

<%= link_to 'Show', @donor %> |
<%= link_to 'Back', donors_path %>

app/views/donors/index.html.erb
<h1>Listing donors</h1>
<p>To edit your details, please drop a mail to <b>mukesh.eledath@gmail.com</b> from your provided email</p>

<table>
  <tr>
    <th>Name</th>
    <th>Contact</th>
    <th>Blood group</th>
    <th>District</th>    
    <th>District</th>
    <th></th>
    <th></th>
  </tr>

<% @donors.each do |donor| %>
  <tr>
    <td><%= donor.name %></td>
    <td><%= donor.contact %></td>
    <td><%= donor.blood_group.bloodgroup %></td>
	<td><%= donor.district %></td>    
    <td><%= link_to 'Show', donor %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Donor', new_donor_path %>

app/views/donors/new.html.erb
<h1>New donor</h1>

<%= render 'form' %>

<%= link_to 'Back', donors_path %>

app/views/donors/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @donor.name %>
</p>

<p>
  <b>Contact:</b>
  <%= @donor.contact %>
</p>

<p>
  <b>Blood group:</b>
  <%= @donor.blood_group.bloodgroup %>
</p>


<%= link_to 'Back', donors_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Bloodbank</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>